### PR TITLE
(chore): Test cases for sub-dir in 'bucket'

### PR DESCRIPTION
**Pull request by niheaven**
Test cases for https://github.com/ScoopInstaller/Scoop/pull/5119

- Relates to https://github.com/ScoopInstaller/Scoop/pull/5119

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by niheaven** [comment]
The above comments and PullRequestHandler failed because `checkver` and `checkhashes` could not fould nested manifests, and that are fixed in ScoopInstaller/Scoop/pull/5119 already.

**Review by rashil2000 — APPROVED** [review]

**Pull request merged**
