### PR TITLE
Add some manifests for testing

### PR DESCRIPTION
**Pull request by rashil2000**
Testing #2 

Copied 50 manifests (random) from Main bucket.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by chawyehsu — APPROVED** [review]

**Comment by rashil2000** [comment]
@chawyehsu the CI ran only on the first commit of the PR. It should run on each and every commit. I think we should delete this line. https://github.com/ScoopInstaller/Tests/blob/ec58caa9c2d272a1cb957e7341619e8619fcd4b5/.github/workflows/ci.yml#L5

**Review by rasa — APPROVED** [review]

**Comment by rashil2000** [comment]
image

@chawyehsu the test fails but the status is still green 😅 What gives?

**Comment by chawyehsu** [comment]
Need to update `bin/test.ps1` to expose Pester's test result.

https://github.com/chawyehsu/bucket-gh-ci-test/blob/9d09f096a2b2ec169cfc744dee2c4f8fd4190954/bin/test.ps1#L3

**Comment by chawyehsu** [comment]
That's it

**Comment by rashil2000** [comment]
Oh, I wonder why that wasn't required for Appveyor?

Also, we would need to do that here too, right? https://github.com/ScoopInstaller/Scoop/blob/master/bin/test.ps1

**Comment by chawyehsu** [comment]
AppVeyor directly calls `test/bin/test.ps1`, which has exposed the result, from the Core.

https://github.com/ScoopInstaller/Scoop/blob/develop/appveyor.yml#L35
https://github.com/ScoopInstaller/Scoop/blob/develop/test/bin/test.ps1#L11

For a bucket, it can either call `test/bin/test.ps1` from the Core directly or call the wrapper `bin/test.ps1` from itself.

**Pull request merged**
